config/routes.rb
Rails.application.routes.draw do
  resources :words
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/word.rb
class Word < ApplicationRecord
    validates :term, presence: true, uniqueness: true
    validates :definition, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: %i[ show edit update destroy ]

  # GET /words or /words.json
  def index
    @words = Word.order(:term)
  end

  # GET /words/1 or /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words or /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: "Word was successfully created." }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1 or /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: "Word was successfully updated." }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1 or /words/1.json
  def destroy
    @word.destroy!

    respond_to do |format|
      format.html { redirect_to words_path, status: :see_other, notice: "Word was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def word_params
      params.require(:word).permit(:term, :definition)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dev Dictionary" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
	  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	  <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">
	  <link rel="preconnect" href="https://fonts.googleapis.com">
	  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	  <link href="https://fonts.googleapis.com/css2?family=Silkscreen:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/_form.html.erb
<%= form_with(model: word) do |form| %>
  <% if word.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
        <% word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :term, style: "display: block" %>
    <%= form.text_field :term %>
  </div>

  <div>
    <%= form.label :definition, style: "display: block" %>
    <%= form.text_area :definition %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/words/_word.html.erb
<div id="<%= dom_id word %>">
  <p>
    <strong>Term:</strong>
    <%= word.term %>
  </p>

  <p>
    <strong>Definition:</strong>
    <%= word.definition %>
  </p>

</div>

app/views/words/edit.html.erb
<% content_for :title, "Editing word" %>

<h1>Editing word</h1>

<%= render "form", word: @word %>

<br>

<div>
  <%= link_to "Show this word", @word %> |
  <%= link_to "Back to words", words_path %>
</div>

app/views/words/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Words" %>

<div class="container">
  <h1>Dicionário</h1>
  <div id="words" class="diktionary">
    <ul id="minhaLista">
    <% @words.each do |word| %>
      <li><strong><%= word.term %>:</strong> <%= word.definition %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/words/new.html.erb
<% content_for :title, "New word" %>

<h1>New word</h1>

<%= render "form", word: @word %>

<br>

<div>
  <%= link_to "Back to words", words_path %>
</div>

app/views/words/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @word %>

<div>
  <%= link_to "Edit this word", edit_word_path(@word) %> |
  <%= link_to "Back to words", words_path %>

  <%= button_to "Destroy this word", @word, method: :delete %>
</div>